spring:
  application:
    name: kafka-streams
  profiles:
    active: local

app:
  run-simulators: ${RUN_SIMULATORS:false}
  vessel-visit:
    id-length: 2

server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: "/api"

#management:
#  health:
#    defaults:
#      enabled: true
#  endpoint:
#    env:
#      enabled: true
#    info:
#      enabled: true
#    mappings:
#      enabled: true
#    health:
#      probes:
#        enabled: true

logging:
  charset:
    console: UTF-8
  level:
    root: info
#    io:
#      micrometer: info
#      netty: info
    org:
      apache:
        kafka: warn
#      hibernate: info
#      jboss: info
      springframework:
#        beans: info
#        boot: info
#        context: info
#        jmx: info
        web: info
#          client:
#            RestTemplate: debug
    com.pvoeten: debug
    com.pvoeten.kafkastreams.api: warn

    reactor:
      netty: info
      util: info

kafka:
  bootstrap-servers: ""
  replication-factor: 1
  allow-topic-creation: false
  state-dir: /kafka-streams
