spring:
  application:
    name: kafka-streams
  profiles:
    active: local

server:
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: "/api"

logging:
  charset:
    console: UTF-8
  level:
    root: info
    org.apache.kafka: warn
    org.springframework.web: info
    org.springframework.web.client.RestTemplate: debug
    com.pvoeten: debug
    com.pvoeten.kafkastreams.api: info

kafka:
  bootstrap-servers: ""
  replication-factor: 1
  allow-topic-creation: false
  state-dir: ${KAFKA_STATE_DIR:/tmp/kafka-streams}
