spring:
  application:
    name: kafka-streams-sim
  profiles:
    active: local

generate:
  bill-of-lading:
    interval: ${BL_GEN_INTERVAL:500}
    amount: ${BL_GEN_AMOUNT:5}
  vessel-visit:
    id-length: ${VV_ID_LENGTH:5}
    interval: ${VV_GEN_INTERVAL:500}
    amount: ${VV_GEN_AMOUNT:5}

logging:
  charset:
    console: UTF-8
  level:
    root: info

kafka:
  bootstrap-servers: ""
